import { ThemePreset } from '../types';

export interface ThemeDefinition {
  id: ThemePreset;
  nameTh: string;
  nameEn: string;
  bgClass: string;
  cardBgClass: string;
  textPrimaryClass: string;
  textSecondaryClass: string;
  textAccentClass: string;
  accentBorderClass: string;
  glowClass: string;
  colonClass: string;
  progressColor: string;
  tagBgClass: string;
  isLight?: boolean;
}

export const THEMES: Record<ThemePreset, ThemeDefinition> = {
  'bold-typography': {
    id: 'bold-typography',
    nameTh: 'ตัวหนา โดดเด่น (Bold)',
    nameEn: 'Bold Typography',
    bgClass: 'bg-[#080808] text-[#FFFFFF]',
    cardBgClass: 'bg-white/5 border-white/10 backdrop-blur-md',
    textPrimaryClass: 'text-white',
    textSecondaryClass: 'text-zinc-400',
    textAccentClass: 'text-indigo-400',
    accentBorderClass: 'border-white/10',
    glowClass: 'text-glow-white',
    colonClass: 'text-indigo-400',
    progressColor: '#6366f1',
    tagBgClass: 'bg-white/5 text-zinc-300 border border-white/10',
  },
  oled: {
    id: 'oled',
    nameTh: 'OLED ดำสนิท',
    nameEn: 'OLED Pure Black',
    bgClass: 'bg-black text-white',
    cardBgClass: 'bg-zinc-900/60 border-zinc-800/80',
    textPrimaryClass: 'text-zinc-100',
    textSecondaryClass: 'text-zinc-400',
    textAccentClass: 'text-zinc-200',
    accentBorderClass: 'border-zinc-800',
    glowClass: 'text-glow-white',
    colonClass: 'text-zinc-400',
    progressColor: '#e4e4e7',
    tagBgClass: 'bg-zinc-800/80 text-zinc-300 border border-zinc-700/50',
  },
  'cyber-cyan': {
    id: 'cyber-cyan',
    nameTh: 'ไซเบอร์ นีออนฟ้า',
    nameEn: 'Cyber Cyan',
    bgClass: 'bg-[#050b14] text-cyan-50',
    cardBgClass: 'bg-cyan-950/30 border-cyan-500/20 backdrop-blur-md',
    textPrimaryClass: 'text-cyan-300',
    textSecondaryClass: 'text-cyan-400/70',
    textAccentClass: 'text-cyan-400',
    accentBorderClass: 'border-cyan-500/30',
    glowClass: 'text-glow-cyan',
    colonClass: 'text-cyan-400',
    progressColor: '#06b6d4',
    tagBgClass: 'bg-cyan-950/60 text-cyan-300 border border-cyan-500/40',
  },
  'sunset-amber': {
    id: 'sunset-amber',
    nameTh: 'แสงสนธยา สีทอง',
    nameEn: 'Sunset Amber',
    bgClass: 'bg-[#0f0a05] text-amber-50',
    cardBgClass: 'bg-amber-950/25 border-amber-500/20 backdrop-blur-md',
    textPrimaryClass: 'text-amber-400',
    textSecondaryClass: 'text-amber-200/70',
    textAccentClass: 'text-amber-400',
    accentBorderClass: 'border-amber-500/30',
    glowClass: 'text-glow-amber',
    colonClass: 'text-amber-400',
    progressColor: '#f59e0b',
    tagBgClass: 'bg-amber-950/60 text-amber-300 border border-amber-500/40',
  },
  'emerald-zen': {
    id: 'emerald-zen',
    nameTh: 'เซน มรกตเขียว',
    nameEn: 'Emerald Zen',
    bgClass: 'bg-[#040f0a] text-emerald-50',
    cardBgClass: 'bg-emerald-950/25 border-emerald-500/20 backdrop-blur-md',
    textPrimaryClass: 'text-emerald-400',
    textSecondaryClass: 'text-emerald-200/70',
    textAccentClass: 'text-emerald-400',
    accentBorderClass: 'border-emerald-500/30',
    glowClass: 'text-glow-emerald',
    colonClass: 'text-emerald-400',
    progressColor: '#10b981',
    tagBgClass: 'bg-emerald-950/60 text-emerald-300 border border-emerald-500/40',
  },
  'neon-rose': {
    id: 'neon-rose',
    nameTh: 'นีออน กุหลาบชมพู',
    nameEn: 'Neon Rose',
    bgClass: 'bg-[#120409] text-rose-50',
    cardBgClass: 'bg-rose-950/25 border-rose-500/20 backdrop-blur-md',
    textPrimaryClass: 'text-rose-400',
    textSecondaryClass: 'text-rose-200/70',
    textAccentClass: 'text-rose-400',
    accentBorderClass: 'border-rose-500/30',
    glowClass: 'text-glow-rose',
    colonClass: 'text-rose-400',
    progressColor: '#f43f5e',
    tagBgClass: 'bg-rose-950/60 text-rose-300 border border-rose-500/40',
  },
  aurora: {
    id: 'aurora',
    nameTh: 'ออโรร่า แสงเหนือ',
    nameEn: 'Aurora Glow',
    bgClass: 'bg-gradient-to-br from-[#070b19] via-[#091522] to-[#041a1c] text-teal-50',
    cardBgClass: 'bg-teal-950/20 border-teal-500/20 backdrop-blur-md',
    textPrimaryClass: 'text-teal-200',
    textSecondaryClass: 'text-teal-300/70',
    textAccentClass: 'text-teal-300',
    accentBorderClass: 'border-teal-500/30',
    glowClass: 'text-glow-cyan',
    colonClass: 'text-teal-400',
    progressColor: '#2dd4bf',
    tagBgClass: 'bg-teal-950/60 text-teal-300 border border-teal-500/30',
  },
  'nordic-slate': {
    id: 'nordic-slate',
    nameTh: 'นอร์ดิก สีสเลท',
    nameEn: 'Nordic Slate',
    bgClass: 'bg-[#0f172a] text-slate-100',
    cardBgClass: 'bg-slate-800/50 border-slate-700/60 backdrop-blur-md',
    textPrimaryClass: 'text-slate-100',
    textSecondaryClass: 'text-slate-400',
    textAccentClass: 'text-sky-400',
    accentBorderClass: 'border-slate-700',
    glowClass: 'text-glow-white',
    colonClass: 'text-sky-400',
    progressColor: '#38bdf8',
    tagBgClass: 'bg-slate-800/90 text-slate-300 border border-slate-700',
  },
  'warm-paper': {
    id: 'warm-paper',
    nameTh: 'กระดาษอุ่น วินเทจ',
    nameEn: 'Warm Espresso',
    bgClass: 'bg-[#181512] text-[#f4efe6]',
    cardBgClass: 'bg-[#241f1a]/80 border-[#3d342c] backdrop-blur-md',
    textPrimaryClass: 'text-[#fbf7ee]',
    textSecondaryClass: 'text-[#c2b6a3]',
    textAccentClass: 'text-[#e5aa70]',
    accentBorderClass: 'border-[#3d342c]',
    glowClass: 'text-glow-white',
    colonClass: 'text-[#e5aa70]',
    progressColor: '#e5aa70',
    tagBgClass: 'bg-[#2a241e] text-[#d6c7b2] border border-[#3d342c]',
  },
  'clean-light': {
    id: 'clean-light',
    nameTh: 'สว่าง สะอาดตา',
    nameEn: 'Clean Light',
    bgClass: 'bg-zinc-50 text-zinc-900',
    cardBgClass: 'bg-white/80 border-zinc-200/80 shadow-sm backdrop-blur-md',
    textPrimaryClass: 'text-zinc-900',
    textSecondaryClass: 'text-zinc-600',
    textAccentClass: 'text-indigo-600',
    accentBorderClass: 'border-zinc-200',
    glowClass: '',
    colonClass: 'text-indigo-600',
    progressColor: '#4f46e5',
    tagBgClass: 'bg-zinc-100 text-zinc-700 border border-zinc-200',
    isLight: true,
  },
};
