import { ThemePreset } from '../types';

export interface ThemeDefinition {
  id: ThemePreset;
  nameTh: string;
  nameEn: string;
  category: 'pastel-canvas' | 'pastel-dark' | 'pastel-light' | 'classic';
  bgClass: string;
  cardBgClass: string;
  textPrimaryClass: string;
  textSecondaryClass: string;
  textAccentClass: string;
  accentBorderClass: string;
  glowClass: string;
  colonClass: string;
  progressColor: string;
  tagBgClass: string;
  isLight?: boolean;
  ambientGlowPrimary?: string;
  ambientGlowSecondary?: string;
  previewColors: {
    bg: string;
    text: string;
    colon: string;
  };
}

export const THEMES: Record<ThemePreset, ThemeDefinition> = {
  // -------------------------------------------------------------
  // 0. Pastel Canvas Themes (พื้นหลังสีพาสเทลหลากสี ละมุนตา ไม่มืดดำ)
  // -------------------------------------------------------------
  'pastel-canvas-lavender': {
    id: 'pastel-canvas-lavender',
    nameTh: 'พาสเทล ลาเวนเดอร์ ดรีม',
    nameEn: 'Pastel Lavender Dream',
    category: 'pastel-canvas',
    bgClass: 'bg-gradient-to-br from-[#ebe4f9] via-[#e4dcf7] to-[#ded3f5] text-[#2c223c]',
    cardBgClass: 'bg-white/65 border-[#d6c9ee]/70 shadow-xs backdrop-blur-md',
    textPrimaryClass: 'text-[#2c223c]',
    textSecondaryClass: 'text-[#685680]',
    textAccentClass: 'text-[#6d3cc7]',
    accentBorderClass: 'border-[#d6c9ee]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#6d3cc7]',
    progressColor: '#6d3cc7',
    tagBgClass: 'bg-[#ded2f3] text-[#4d2d82] border border-[#cfbef0]',
    isLight: true,
    ambientGlowPrimary: '#c4b5fd',
    ambientGlowSecondary: '#ddd6fe',
    previewColors: { bg: '#e4dcf7', text: '#2c223c', colon: '#6d3cc7' },
  },
  'pastel-canvas-matcha': {
    id: 'pastel-canvas-matcha',
    nameTh: 'พาสเทล มัทฉะ & เซจ',
    nameEn: 'Pastel Matcha & Sage',
    category: 'pastel-canvas',
    bgClass: 'bg-gradient-to-br from-[#e6f3eb] via-[#d7ece0] to-[#cbe5d5] text-[#1a2d20]',
    cardBgClass: 'bg-white/65 border-[#bfe0cc]/70 shadow-xs backdrop-blur-md',
    textPrimaryClass: 'text-[#1a2d20]',
    textSecondaryClass: 'text-[#4c6f55]',
    textAccentClass: 'text-[#1d773c]',
    accentBorderClass: 'border-[#bfe0cc]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#1d773c]',
    progressColor: '#1d773c',
    tagBgClass: 'bg-[#d5eadc] text-[#215430] border border-[#bee0cb]',
    isLight: true,
    ambientGlowPrimary: '#86efac',
    ambientGlowSecondary: '#bbf7d0',
    previewColors: { bg: '#d7ece0', text: '#1a2d20', colon: '#1d773c' },
  },
  'pastel-canvas-sky': {
    id: 'pastel-canvas-sky',
    nameTh: 'พาสเทล เบบี้บลู สกาย',
    nameEn: 'Pastel Baby Blue Sky',
    category: 'pastel-canvas',
    bgClass: 'bg-gradient-to-br from-[#e4f1fb] via-[#d4e8f7] to-[#c8e2f6] text-[#182a3d]',
    cardBgClass: 'bg-white/65 border-[#badaf5]/70 shadow-xs backdrop-blur-md',
    textPrimaryClass: 'text-[#182a3d]',
    textSecondaryClass: 'text-[#4a6b8f]',
    textAccentClass: 'text-[#0270c4]',
    accentBorderClass: 'border-[#badaf5]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#0270c4]',
    progressColor: '#0270c4',
    tagBgClass: 'bg-[#d2e7f8] text-[#154673] border border-[#badaf5]',
    isLight: true,
    ambientGlowPrimary: '#93c5fd',
    ambientGlowSecondary: '#bae6fd',
    previewColors: { bg: '#d4e8f7', text: '#182a3d', colon: '#0270c4' },
  },
  'pastel-canvas-peach': {
    id: 'pastel-canvas-peach',
    nameTh: 'พาสเทล พีช & แอปริคอต',
    nameEn: 'Pastel Peach & Apricot',
    category: 'pastel-canvas',
    bgClass: 'bg-gradient-to-br from-[#fbeee6] via-[#f7ded2] to-[#f2cfc0] text-[#362218]',
    cardBgClass: 'bg-white/65 border-[#f1c4b2]/70 shadow-xs backdrop-blur-md',
    textPrimaryClass: 'text-[#362218]',
    textSecondaryClass: 'text-[#7b5443]',
    textAccentClass: 'text-[#be461c]',
    accentBorderClass: 'border-[#f1c4b2]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#be461c]',
    progressColor: '#be461c',
    tagBgClass: 'bg-[#f6dad0] text-[#6d2a13] border border-[#f1c4b2]',
    isLight: true,
    ambientGlowPrimary: '#fdba74',
    ambientGlowSecondary: '#fed7aa',
    previewColors: { bg: '#f7ded2', text: '#362218', colon: '#be461c' },
  },
  'pastel-canvas-sakura': {
    id: 'pastel-canvas-sakura',
    nameTh: 'พาสเทล ซากุระ บลอสซั่ม',
    nameEn: 'Pastel Sakura Blossom',
    category: 'pastel-canvas',
    bgClass: 'bg-gradient-to-br from-[#fae8f0] via-[#f6d7e5] to-[#f0c7db] text-[#361e2b]',
    cardBgClass: 'bg-white/65 border-[#eebed5]/70 shadow-xs backdrop-blur-md',
    textPrimaryClass: 'text-[#361e2b]',
    textSecondaryClass: 'text-[#7b4c65]',
    textAccentClass: 'text-[#b8185b]',
    accentBorderClass: 'border-[#eebed5]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#b8185b]',
    progressColor: '#b8185b',
    tagBgClass: 'bg-[#f4d4e3] text-[#711b46] border border-[#eebed5]',
    isLight: true,
    ambientGlowPrimary: '#f472b6',
    ambientGlowSecondary: '#f9a8d4',
    previewColors: { bg: '#f6d7e5', text: '#361e2b', colon: '#b8185b' },
  },
  'pastel-canvas-butter': {
    id: 'pastel-canvas-butter',
    nameTh: 'พาสเทล ครีม & วานิลลา',
    nameEn: 'Pastel Vanilla Butter',
    category: 'pastel-canvas',
    bgClass: 'bg-gradient-to-br from-[#faf4e6] via-[#f5e9ce] to-[#efddb7] text-[#332918]',
    cardBgClass: 'bg-white/65 border-[#e8d7b0]/70 shadow-xs backdrop-blur-md',
    textPrimaryClass: 'text-[#332918]',
    textSecondaryClass: 'text-[#6e5d3c]',
    textAccentClass: 'text-[#b25109]',
    accentBorderClass: 'border-[#e8d7b0]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#b25109]',
    progressColor: '#b25109',
    tagBgClass: 'bg-[#f2e4c5] text-[#633909] border border-[#e8d7b0]',
    isLight: true,
    ambientGlowPrimary: '#fde68a',
    ambientGlowSecondary: '#fcd34d',
    previewColors: { bg: '#f5e9ce', text: '#332918', colon: '#b25109' },
  },
  'pastel-canvas-rainbow': {
    id: 'pastel-canvas-rainbow',
    nameTh: 'พาสเทล คอตตอนแคนดี้ (ไล่เฉดสี)',
    nameEn: 'Pastel Cotton Candy Gradient',
    category: 'pastel-canvas',
    bgClass: 'bg-gradient-to-br from-[#ece4f9] via-[#fae8f0] to-[#e1edf8] text-[#2c223c]',
    cardBgClass: 'bg-white/65 border-[#dad0ee]/70 shadow-xs backdrop-blur-md',
    textPrimaryClass: 'text-[#2c223c]',
    textSecondaryClass: 'text-[#685680]',
    textAccentClass: 'text-[#793aeb]',
    accentBorderClass: 'border-[#dad0ee]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#793aeb]',
    progressColor: '#793aeb',
    tagBgClass: 'bg-[#e7dcf7] text-[#522588] border border-[#dad0ee]',
    isLight: true,
    ambientGlowPrimary: '#c4b5fd',
    ambientGlowSecondary: '#f9a8d4',
    previewColors: { bg: '#ece4f9', text: '#2c223c', colon: '#793aeb' },
  },
  'pastel-canvas-sunset': {
    id: 'pastel-canvas-sunset',
    nameTh: 'พาสเทล ซันเซ็ต โกลว์',
    nameEn: 'Pastel Sunset Glow',
    category: 'pastel-canvas',
    bgClass: 'bg-gradient-to-br from-[#faebe3] via-[#f7dbe8] to-[#ebe3f8] text-[#33202e]',
    cardBgClass: 'bg-white/65 border-[#eccfda]/70 shadow-xs backdrop-blur-md',
    textPrimaryClass: 'text-[#33202e]',
    textSecondaryClass: 'text-[#744d6b]',
    textAccentClass: 'text-[#9c18a8]',
    accentBorderClass: 'border-[#eccfda]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#9c18a8]',
    progressColor: '#9c18a8',
    tagBgClass: 'bg-[#f2d9e5] text-[#64185d] border border-[#eccfda]',
    isLight: true,
    ambientGlowPrimary: '#fed7aa',
    ambientGlowSecondary: '#f9a8d4',
    previewColors: { bg: '#f7dbe8', text: '#33202e', colon: '#9c18a8' },
  },
  'pastel-canvas-ocean-breeze': {
    id: 'pastel-canvas-ocean-breeze',
    nameTh: 'พาสเทล ซีบรีซ (มิ้นต์ & สกาย)',
    nameEn: 'Pastel Sea Breeze',
    category: 'pastel-canvas',
    bgClass: 'bg-gradient-to-br from-[#e2f4ed] via-[#d6edf2] to-[#d6e5f8] text-[#172b35]',
    cardBgClass: 'bg-white/65 border-[#c0e0e9]/70 shadow-xs backdrop-blur-md',
    textPrimaryClass: 'text-[#172b35]',
    textSecondaryClass: 'text-[#486e7e]',
    textAccentClass: 'text-[#0c8f83]',
    accentBorderClass: 'border-[#c0e0e9]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#0c8f83]',
    progressColor: '#0c8f83',
    tagBgClass: 'bg-[#d2e9ef] text-[#135461] border border-[#c0e0e9]',
    isLight: true,
    ambientGlowPrimary: '#99f6e4',
    ambientGlowSecondary: '#bae6fd',
    previewColors: { bg: '#d6edf2', text: '#172b35', colon: '#0c8f83' },
  },

  // -------------------------------------------------------------
  // 1. Pastel Dark / Night Themes (ถนอมสายตา นุ่มนวล สีตัดกันพอดี)
  // -------------------------------------------------------------
  'pastel-matcha': {
    id: 'pastel-matcha',
    nameTh: 'มัทฉะ & เซจ (ถนอมสายตา)',
    nameEn: 'Pastel Matcha & Sage',
    category: 'pastel-dark',
    bgClass: 'bg-[#0f1512] text-[#edf7f0]',
    cardBgClass: 'bg-[#152119]/70 border-[#233327]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#edf7f0]',
    textSecondaryClass: 'text-[#92b899]',
    textAccentClass: 'text-[#86efac]',
    accentBorderClass: 'border-[#233327]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#86efac]',
    progressColor: '#86efac',
    tagBgClass: 'bg-[#16291c] text-[#bbf7d0] border border-[#233d2a]',
    ambientGlowPrimary: '#86efac',
    ambientGlowSecondary: '#a7f3d0',
    previewColors: { bg: '#0f1512', text: '#edf7f0', colon: '#86efac' },
  },
  'pastel-lavender': {
    id: 'pastel-lavender',
    nameTh: 'ลาเวนเดอร์ & ไลแลค (นุ่มตา)',
    nameEn: 'Pastel Lavender & Lilac',
    category: 'pastel-dark',
    bgClass: 'bg-[#12111a] text-[#f5f2fb]',
    cardBgClass: 'bg-[#1a1726]/70 border-[#2e263d]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#f5f2fb]',
    textSecondaryClass: 'text-[#a99fc7]',
    textAccentClass: 'text-[#c4b5fd]',
    accentBorderClass: 'border-[#2e263d]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#c4b5fd]',
    progressColor: '#c4b5fd',
    tagBgClass: 'bg-[#201a30] text-[#ddd6fe] border border-[#322847]',
    ambientGlowPrimary: '#c4b5fd',
    ambientGlowSecondary: '#ddd6fe',
    previewColors: { bg: '#12111a', text: '#f5f2fb', colon: '#c4b5fd' },
  },
  'pastel-sky': {
    id: 'pastel-sky',
    nameTh: 'เบบี้บลู & สกาย (นุ่มสบายตา)',
    nameEn: 'Pastel Baby Blue & Sky',
    category: 'pastel-dark',
    bgClass: 'bg-[#0d131c] text-[#edf4fc]',
    cardBgClass: 'bg-[#141f2e]/70 border-[#202f45]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#edf4fc]',
    textSecondaryClass: 'text-[#90a8c7]',
    textAccentClass: 'text-[#93c5fd]',
    accentBorderClass: 'border-[#202f45]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#93c5fd]',
    progressColor: '#93c5fd',
    tagBgClass: 'bg-[#162538] text-[#bfdbfe] border border-[#243954]',
    ambientGlowPrimary: '#93c5fd',
    ambientGlowSecondary: '#7dd3fc',
    previewColors: { bg: '#0d131c', text: '#edf4fc', colon: '#93c5fd' },
  },
  'pastel-peach': {
    id: 'pastel-peach',
    nameTh: 'พีช & แอปริคอต (อุ่นละมุน)',
    nameEn: 'Pastel Peach & Apricot',
    category: 'pastel-dark',
    bgClass: 'bg-[#15110e] text-[#faf3ee]',
    cardBgClass: 'bg-[#211915]/70 border-[#362720]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#faf3ee]',
    textSecondaryClass: 'text-[#c7a591]',
    textAccentClass: 'text-[#fed7aa]',
    accentBorderClass: 'border-[#362720]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#fed7aa]',
    progressColor: '#fed7aa',
    tagBgClass: 'bg-[#291e17] text-[#fed7aa] border border-[#402d23]',
    ambientGlowPrimary: '#fdba74',
    ambientGlowSecondary: '#fca5a5',
    previewColors: { bg: '#15110e', text: '#faf3ee', colon: '#fed7aa' },
  },
  'pastel-rose': {
    id: 'pastel-rose',
    nameTh: 'ซากุระ & ดัสตี้โรส (ถนอมสายตา)',
    nameEn: 'Pastel Sakura & Dusty Rose',
    category: 'pastel-dark',
    bgClass: 'bg-[#150f13] text-[#fbf1f5]',
    cardBgClass: 'bg-[#21151d]/70 border-[#382130]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#fbf1f5]',
    textSecondaryClass: 'text-[#c995ad]',
    textAccentClass: 'text-[#f9a8d4]',
    accentBorderClass: 'border-[#382130]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#f9a8d4]',
    progressColor: '#f9a8d4',
    tagBgClass: 'bg-[#291723] text-[#fce7f3] border border-[#3d2235]',
    ambientGlowPrimary: '#f472b6',
    ambientGlowSecondary: '#f9a8d4',
    previewColors: { bg: '#150f13', text: '#fbf1f5', colon: '#f9a8d4' },
  },
  'pastel-mint': {
    id: 'pastel-mint',
    nameTh: 'มินต์ & ซีโฟม (เย็นสบายตา)',
    nameEn: 'Pastel Mint & Seafoam',
    category: 'pastel-dark',
    bgClass: 'bg-[#0c1414] text-[#ecf8f6]',
    cardBgClass: 'bg-[#132020]/70 border-[#1f3333]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#ecf8f6]',
    textSecondaryClass: 'text-[#87b8b4]',
    textAccentClass: 'text-[#99f6e4]',
    accentBorderClass: 'border-[#1f3333]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#99f6e4]',
    progressColor: '#5eead4',
    tagBgClass: 'bg-[#172929] text-[#ccfbf1] border border-[#213f3e]',
    ambientGlowPrimary: '#5eead4',
    ambientGlowSecondary: '#99f6e4',
    previewColors: { bg: '#0c1414', text: '#ecf8f6', colon: '#99f6e4' },
  },
  'pastel-honey': {
    id: 'pastel-honey',
    nameTh: 'วานิลลา & ฮันนี่ (อุ่นสบายตา)',
    nameEn: 'Pastel Vanilla & Honey',
    category: 'pastel-dark',
    bgClass: 'bg-[#14120c] text-[#faf8ee]',
    cardBgClass: 'bg-[#1f1b12]/70 border-[#332c1c]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#faf8ee]',
    textSecondaryClass: 'text-[#c4b98e]',
    textAccentClass: 'text-[#fde68a]',
    accentBorderClass: 'border-[#332c1c]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#fde68a]',
    progressColor: '#fde68a',
    tagBgClass: 'bg-[#262114] text-[#fef08a] border border-[#3b3420]',
    ambientGlowPrimary: '#fde047',
    ambientGlowSecondary: '#fcd34d',
    previewColors: { bg: '#14120c', text: '#faf8ee', colon: '#fde68a' },
  },
  'pastel-nordic-haze': {
    id: 'pastel-nordic-haze',
    nameTh: 'นอร์ดิก หมอกพาสเทล',
    nameEn: 'Pastel Nordic Haze',
    category: 'pastel-dark',
    bgClass: 'bg-[#10141c] text-[#edf2f7]',
    cardBgClass: 'bg-[#171e2b]/70 border-[#242f44]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#edf2f7]',
    textSecondaryClass: 'text-[#8796ab]',
    textAccentClass: 'text-[#a5b4fc]',
    accentBorderClass: 'border-[#242f44]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#a5b4fc]',
    progressColor: '#a5b4fc',
    tagBgClass: 'bg-[#1c2436] text-[#c7d2fe] border border-[#2b3752]',
    ambientGlowPrimary: '#a5b4fc',
    ambientGlowSecondary: '#818cf8',
    previewColors: { bg: '#10141c', text: '#edf2f7', colon: '#a5b4fc' },
  },
  'pastel-twilight-charcoal': {
    id: 'pastel-twilight-charcoal',
    nameTh: 'ทไวไลท์ ชาร์โคล (มินิมอลเงียบสงบ)',
    nameEn: 'Pastel Twilight Charcoal',
    category: 'pastel-dark',
    bgClass: 'bg-[#111215] text-[#f1f5f9]',
    cardBgClass: 'bg-[#18191d]/70 border-[#26272e]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#f1f5f9]',
    textSecondaryClass: 'text-[#8892a2]',
    textAccentClass: 'text-[#cbd5e1]',
    accentBorderClass: 'border-[#26272e]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#cbd5e1]',
    progressColor: '#cbd5e1',
    tagBgClass: 'bg-[#1d1e24] text-[#e2e8f0] border border-[#2b2d36]',
    ambientGlowPrimary: '#cbd5e1',
    ambientGlowSecondary: '#94a3b8',
    previewColors: { bg: '#111215', text: '#f1f5f9', colon: '#cbd5e1' },
  },

  // -------------------------------------------------------------
  // 2. Pastel Light / Daytime Themes (โทนสว่างนวล สบายตา ไม่สะท้อน)
  // -------------------------------------------------------------
  'pastel-oatmilk': {
    id: 'pastel-oatmilk',
    nameTh: 'โอ๊ตมิลค์ & วานิลลา (ละมุนตา)',
    nameEn: 'Pastel Oat Milk & Vanilla',
    category: 'pastel-light',
    isLight: true,
    bgClass: 'bg-[#f5f2eb] text-[#2d2724]',
    cardBgClass: 'bg-white/75 border-[#e5dfd4] shadow-none backdrop-blur-md',
    textPrimaryClass: 'text-[#2d2724]',
    textSecondaryClass: 'text-[#786f68]',
    textAccentClass: 'text-[#9a3412]',
    accentBorderClass: 'border-[#e5dfd4]',
    glowClass: '',
    colonClass: 'text-[#a8441f]',
    progressColor: '#a8441f',
    tagBgClass: 'bg-[#ebe5d8] text-[#524942] border border-[#d8d0c0]',
    ambientGlowPrimary: '#fed7aa',
    ambientGlowSecondary: '#fde68a',
    previewColors: { bg: '#f5f2eb', text: '#2d2724', colon: '#a8441f' },
  },
  'pastel-sky-light': {
    id: 'pastel-sky-light',
    nameTh: 'คลาวด์บลู หมอกเช้า (สว่างนุ่ม)',
    nameEn: 'Pastel Cloud Blue Mist',
    category: 'pastel-light',
    isLight: true,
    bgClass: 'bg-[#edf2f7] text-[#1e293b]',
    cardBgClass: 'bg-white/75 border-[#d6e0ec] shadow-none backdrop-blur-md',
    textPrimaryClass: 'text-[#1e293b]',
    textSecondaryClass: 'text-[#5d7189]',
    textAccentClass: 'text-[#0369a1]',
    accentBorderClass: 'border-[#d6e0ec]',
    glowClass: '',
    colonClass: 'text-[#0284c7]',
    progressColor: '#0284c7',
    tagBgClass: 'bg-[#dde7f2] text-[#2c3d52] border border-[#c6d7e8]',
    ambientGlowPrimary: '#bae6fd',
    ambientGlowSecondary: '#e0f2fe',
    previewColors: { bg: '#edf2f7', text: '#1e293b', colon: '#0284c7' },
  },
  'pastel-matcha-light': {
    id: 'pastel-matcha-light',
    nameTh: 'มัทฉะครีม (สว่างธรรมชาติ)',
    nameEn: 'Pastel Matcha Cream',
    category: 'pastel-light',
    isLight: true,
    bgClass: 'bg-[#eef4f0] text-[#1b2820]',
    cardBgClass: 'bg-white/75 border-[#d2dfd6] shadow-none backdrop-blur-md',
    textPrimaryClass: 'text-[#1b2820]',
    textSecondaryClass: 'text-[#4e6d55]',
    textAccentClass: 'text-[#15803d]',
    accentBorderClass: 'border-[#d2dfd6]',
    glowClass: '',
    colonClass: 'text-[#15803d]',
    progressColor: '#15803d',
    tagBgClass: 'bg-[#dde9df] text-[#293d2e] border border-[#c5d8c9]',
    ambientGlowPrimary: '#bbf7d0',
    ambientGlowSecondary: '#dcfce7',
    previewColors: { bg: '#eef4f0', text: '#1b2820', colon: '#15803d' },
  },
  'pastel-lilac-light': {
    id: 'pastel-lilac-light',
    nameTh: 'ไลแลคบลอสซั่ม (สว่างอบอุ่น)',
    nameEn: 'Pastel Lilac Blossom',
    category: 'pastel-light',
    isLight: true,
    bgClass: 'bg-[#f3eff7] text-[#261c2e]',
    cardBgClass: 'bg-white/75 border-[#e3d7ea] shadow-none backdrop-blur-md',
    textPrimaryClass: 'text-[#261c2e]',
    textSecondaryClass: 'text-[#6c587d]',
    textAccentClass: 'text-[#6d28d9]',
    accentBorderClass: 'border-[#e3d7ea]',
    glowClass: '',
    colonClass: 'text-[#6d28d9]',
    progressColor: '#6d28d9',
    tagBgClass: 'bg-[#ebdff2] text-[#3e2e4b] border border-[#d8c5e3]',
    ambientGlowPrimary: '#ddd6fe',
    ambientGlowSecondary: '#ede9fe',
    previewColors: { bg: '#f3eff7', text: '#261c2e', colon: '#6d28d9' },
  },

  // -------------------------------------------------------------
  // 3. Minimalist Classics (ปรับแต่งใหม่ สบายตา ไม่จ้า ไม่แสบ)
  // -------------------------------------------------------------
  'bold-typography': {
    id: 'bold-typography',
    nameTh: 'ตัวหนา มินิมอล ชาร์โคล (Bold)',
    nameEn: 'Bold Typography Minimal',
    category: 'classic',
    bgClass: 'bg-[#101114] text-[#eaeef4]',
    cardBgClass: 'bg-white/[0.04] border-white/[0.08] backdrop-blur-md',
    textPrimaryClass: 'text-[#eaeef4]',
    textSecondaryClass: 'text-zinc-400',
    textAccentClass: 'text-[#94a3b8]',
    accentBorderClass: 'border-white/[0.08]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#94a3b8]',
    progressColor: '#94a3b8',
    tagBgClass: 'bg-white/[0.05] text-zinc-300 border border-white/[0.08]',
    ambientGlowPrimary: '#94a3b8',
    ambientGlowSecondary: '#64748b',
    previewColors: { bg: '#101114', text: '#eaeef4', colon: '#94a3b8' },
  },
  oled: {
    id: 'oled',
    nameTh: 'OLED ดำสนิท มินิมอล (ถนอมตา)',
    nameEn: 'OLED Pure Black Minimal',
    category: 'classic',
    bgClass: 'bg-black text-[#d4d4d8]',
    cardBgClass: 'bg-zinc-900/50 border-zinc-800/60',
    textPrimaryClass: 'text-[#d4d4d8]',
    textSecondaryClass: 'text-zinc-500',
    textAccentClass: 'text-zinc-400',
    accentBorderClass: 'border-zinc-800/80',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#71717a]',
    progressColor: '#a1a1aa',
    tagBgClass: 'bg-zinc-900 text-zinc-400 border border-zinc-800',
    ambientGlowPrimary: '#71717a',
    ambientGlowSecondary: '#52525b',
    previewColors: { bg: '#000000', text: '#d4d4d8', colon: '#71717a' },
  },
  'cyber-cyan': {
    id: 'cyber-cyan',
    nameTh: 'ไอซ์บลู นอร์ดิก มินิมอล',
    nameEn: 'Nordic Ice Blue Minimal',
    category: 'classic',
    bgClass: 'bg-[#0d1319] text-[#edf6fb]',
    cardBgClass: 'bg-[#13202a]/60 border-[#1f3343]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#edf6fb]',
    textSecondaryClass: 'text-[#84a9c2]',
    textAccentClass: 'text-[#7dd3fc]',
    accentBorderClass: 'border-[#1f3343]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#7dd3fc]',
    progressColor: '#7dd3fc',
    tagBgClass: 'bg-[#182936] text-[#bae6fd] border border-[#244158]',
    ambientGlowPrimary: '#7dd3fc',
    ambientGlowSecondary: '#38bdf8',
    previewColors: { bg: '#0d1319', text: '#edf6fb', colon: '#7dd3fc' },
  },
  'sunset-amber': {
    id: 'sunset-amber',
    nameTh: 'ซันเซ็ต แอมเบอร์ นุ่มนวล',
    nameEn: 'Soft Sunset Amber',
    category: 'classic',
    bgClass: 'bg-[#14110d] text-[#faf6ee]',
    cardBgClass: 'bg-[#201a14]/60 border-[#332a20]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#faf6ee]',
    textSecondaryClass: 'text-[#c4ad95]',
    textAccentClass: 'text-[#fed7aa]',
    accentBorderClass: 'border-[#332a20]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#fed7aa]',
    progressColor: '#fed7aa',
    tagBgClass: 'bg-[#282018] text-[#fed7aa] border border-[#3d3023]',
    ambientGlowPrimary: '#fed7aa',
    ambientGlowSecondary: '#fbbf24',
    previewColors: { bg: '#14110d', text: '#faf6ee', colon: '#fed7aa' },
  },
  'emerald-zen': {
    id: 'emerald-zen',
    nameTh: 'เซน การ์เด้น มรกตพาสเทล',
    nameEn: 'Zen Garden Soft Emerald',
    category: 'classic',
    bgClass: 'bg-[#0c1410] text-[#ecf7f1]',
    cardBgClass: 'bg-[#13211a]/60 border-[#1e342a]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#ecf7f1]',
    textSecondaryClass: 'text-[#85b59a]',
    textAccentClass: 'text-[#a7f3d0]',
    accentBorderClass: 'border-[#1e342a]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#a7f3d0]',
    progressColor: '#a7f3d0',
    tagBgClass: 'bg-[#172b21] text-[#bbf7d0] border border-[#234233]',
    ambientGlowPrimary: '#a7f3d0',
    ambientGlowSecondary: '#6ee7b7',
    previewColors: { bg: '#0c1410', text: '#ecf7f1', colon: '#a7f3d0' },
  },
  'neon-rose': {
    id: 'neon-rose',
    nameTh: 'ดัสตี้โรส บลัช (ไม่แสบตา)',
    nameEn: 'Dusty Rose Blush Soft',
    category: 'classic',
    bgClass: 'bg-[#140e12] text-[#faf0f4]',
    cardBgClass: 'bg-[#20141d]/60 border-[#33202e]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#faf0f4]',
    textSecondaryClass: 'text-[#c291a9]',
    textAccentClass: 'text-[#fbcfe8]',
    accentBorderClass: 'border-[#33202e]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#fbcfe8]',
    progressColor: '#fbcfe8',
    tagBgClass: 'bg-[#281824] text-[#fce7f3] border border-[#3d2438]',
    ambientGlowPrimary: '#fbcfe8',
    ambientGlowSecondary: '#f472b6',
    previewColors: { bg: '#140e12', text: '#faf0f4', colon: '#fbcfe8' },
  },
  aurora: {
    id: 'aurora',
    nameTh: 'ออโรร่า ละมุนตา',
    nameEn: 'Soft Muted Aurora',
    category: 'classic',
    bgClass: 'bg-[#0c1218] text-[#edf8f6]',
    cardBgClass: 'bg-[#121c24]/60 border-[#1d2d3b]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#edf8f6]',
    textSecondaryClass: 'text-[#87aeb0]',
    textAccentClass: 'text-[#99f6e4]',
    accentBorderClass: 'border-[#1d2d3b]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#99f6e4]',
    progressColor: '#99f6e4',
    tagBgClass: 'bg-[#16252e] text-[#ccfbf1] border border-[#223947]',
    ambientGlowPrimary: '#99f6e4',
    ambientGlowSecondary: '#818cf8',
    previewColors: { bg: '#0c1218', text: '#edf8f6', colon: '#99f6e4' },
  },
  'nordic-slate': {
    id: 'nordic-slate',
    nameTh: 'นอร์ดิก สเลท คลาสสิก',
    nameEn: 'Soft Nordic Slate',
    category: 'classic',
    bgClass: 'bg-[#10141d] text-[#f1f5f9]',
    cardBgClass: 'bg-[#161c28]/60 border-[#232d40]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#f1f5f9]',
    textSecondaryClass: 'text-[#8193a8]',
    textAccentClass: 'text-[#cbd5e1]',
    accentBorderClass: 'border-[#232d40]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#cbd5e1]',
    progressColor: '#cbd5e1',
    tagBgClass: 'bg-[#1c2434] text-[#e2e8f0] border border-[#2b3750]',
    ambientGlowPrimary: '#cbd5e1',
    ambientGlowSecondary: '#94a3b8',
    previewColors: { bg: '#10141d', text: '#f1f5f9', colon: '#cbd5e1' },
  },
  'warm-paper': {
    id: 'warm-paper',
    nameTh: 'กระดาษอุ่น เอสเปรสโซ่',
    nameEn: 'Warm Paper Espresso',
    category: 'classic',
    bgClass: 'bg-[#15120f] text-[#faf6ee]',
    cardBgClass: 'bg-[#201b16]/70 border-[#332b23]/60 backdrop-blur-md',
    textPrimaryClass: 'text-[#faf6ee]',
    textSecondaryClass: 'text-[#baa995]',
    textAccentClass: 'text-[#fed7aa]',
    accentBorderClass: 'border-[#332b23]',
    glowClass: 'text-glow-soft',
    colonClass: 'text-[#fed7aa]',
    progressColor: '#fed7aa',
    tagBgClass: 'bg-[#27211b] text-[#d6c7b2] border border-[#3a3026]',
    ambientGlowPrimary: '#fed7aa',
    ambientGlowSecondary: '#d97706',
    previewColors: { bg: '#15120f', text: '#faf6ee', colon: '#fed7aa' },
  },
  'clean-light': {
    id: 'clean-light',
    nameTh: 'สว่าง สะอาดตา ละมุนตา',
    nameEn: 'Clean Soft Linen Light',
    category: 'classic',
    isLight: true,
    bgClass: 'bg-[#f6f6f7] text-[#222326]',
    cardBgClass: 'bg-white/80 border-zinc-200/70 shadow-none backdrop-blur-md',
    textPrimaryClass: 'text-[#222326]',
    textSecondaryClass: 'text-zinc-500',
    textAccentClass: 'text-[#4f46e5]',
    accentBorderClass: 'border-zinc-200',
    glowClass: '',
    colonClass: 'text-[#4f46e5]',
    progressColor: '#4f46e5',
    tagBgClass: 'bg-zinc-100 text-zinc-700 border border-zinc-200',
    ambientGlowPrimary: '#c7d2fe',
    ambientGlowSecondary: '#e0e7ff',
    previewColors: { bg: '#f6f6f7', text: '#222326', colon: '#4f46e5' },
  },
};

